/**
 * ステージデータ定義
 */

const STAGES = {
  easy: [
    {
      stageName: 'りんご',
      stageEmoji: '🍎',
      target: ['🍎'],
      targetCount: [5],
      distractors: ['🌿'],
      distractorCount: 2,
      moving: false,
      question: ['🍎 は いくつ？'],
    },
    {
      stageName: 'さかな',
      stageEmoji: '🐟',
      target: ['🐟'],
      targetCount: [7],
      distractors: ['🪨'],
      distractorCount: 2,
      moving: false,
      question: ['🐟 は いくつ？'],
    },
    {
      stageName: 'おほし',
      stageEmoji: '⭐',
      target: ['⭐'],
      targetCount: [4],
      distractors: ['☁️'],
      distractorCount: 1,
      moving: false,
      question: ['⭐ は いくつ？'],
    },
    {
      stageName: 'さくら',
      stageEmoji: '🌸',
      target: ['🌸'],
      targetCount: [8],
      distractors: ['🍃'],
      distractorCount: 3,
      moving: false,
      question: ['🌸 は いくつ？'],
    },
    {
      stageName: 'ひよこ',
      stageEmoji: '🐤',
      target: ['🐤'],
      targetCount: [6],
      distractors: ['🌳'],
      distractorCount: 2,
      moving: false,
      question: ['🐤 は いくつ？'],
    },
  ],
  normal: [
    {
      stageName: 'ちょうちょ',
      stageEmoji: '🦋',
      target: ['🦋'],
      targetCount: [6],
      distractors: ['🌼'],
      distractorCount: 3,
      moving: true,
      question: ['🦋 は いくつ？'],
    },
    {
      stageName: 'おさかな',
      stageEmoji: '🐠',
      target: ['🐠'],
      targetCount: [8],
      distractors: ['🫧'],
      distractorCount: 3,
      moving: true,
      question: ['🐠 は いくつ？'],
    },
    {
      stageName: 'はち',
      stageEmoji: '🐝',
      target: ['🐝'],
      targetCount: [5],
      distractors: ['🌻'],
      distractorCount: 2,
      moving: true,
      question: ['🐝 は いくつ？'],
    },
    {
      stageName: 'ふうせん',
      stageEmoji: '🎈',
      target: ['🎈'],
      targetCount: [9],
      distractors: ['☁️'],
      distractorCount: 3,
      moving: true,
      question: ['🎈 は いくつ？'],
    },
    {
      stageName: 'てんとう',
      stageEmoji: '🐞',
      target: ['🐞'],
      targetCount: [7],
      distractors: ['🍀'],
      distractorCount: 2,
      moving: true,
      question: ['🐞 は いくつ？'],
    },
  ],
  hard: [
    {
      stageName: 'りんごとみかん',
      stageEmoji: '🍎🍊',
      target: ['🍎', '🍊'],
      targetCount: [5, 4],
      distractors: ['🌿', '🍂', '🪨'],
      distractorCount: 6,
      moving: true,
      question: ['🍎 は いくつ？', '🍊 は いくつ？'],
    },
    {
      stageName: 'さかなとたこ',
      stageEmoji: '🐟🐙',
      target: ['🐟', '🐙'],
      targetCount: [6, 3],
      distractors: ['🫧', '🪨', '🌊'],
      distractorCount: 7,
      moving: true,
      question: ['🐟 は いくつ？', '🐙 は いくつ？'],
    },
    {
      stageName: 'ほしとつき',
      stageEmoji: '⭐🌙',
      target: ['⭐', '🌙'],
      targetCount: [8, 5],
      distractors: ['☁️', '✈️', '🪁'],
      distractorCount: 6,
      moving: true,
      question: ['⭐ は いくつ？', '🌙 は いくつ？'],
    },
    {
      stageName: 'さくらとはな',
      stageEmoji: '🌸🌺',
      target: ['🌸', '🌺'],
      targetCount: [7, 4],
      distractors: ['🍃', '🐛', '🌿', '🪲'],
      distractorCount: 8,
      moving: true,
      question: ['🌸 は いくつ？', '🌺 は いくつ？'],
    },
    {
      stageName: 'ひよことかえる',
      stageEmoji: '🐤🐸',
      target: ['🐤', '🐸'],
      targetCount: [6, 5],
      distractors: ['🌳', '🍄', '🪺', '🌿'],
      distractorCount: 7,
      moving: true,
      question: ['🐤 は いくつ？', '🐸 は いくつ？'],
    },
  ],
  extra: [
    {
      stageName: 'くじらといるか',
      stageEmoji: '🐋🐬',
      target: ['🐋', '🐬'],
      targetCount: [4, 7],
      distractors: ['🫧', '🪨', '🌊', '🐚', '🦀'],
      distractorCount: 10,
      moving: true,
      question: ['🐋 は いくつ？', '🐬 は いくつ？'],
    },
    {
      stageName: 'けーきとどーなつ',
      stageEmoji: '🎂🍩',
      target: ['🎂', '🍩'],
      targetCount: [5, 8],
      distractors: ['🍬', '🍭', '🧁', '🍪', '🍫'],
      distractorCount: 12,
      moving: true,
      question: ['🎂 は いくつ？', '🍩 は いくつ？'],
    },
    {
      stageName: 'ろけっととほし',
      stageEmoji: '🚀💫',
      target: ['🚀', '💫'],
      targetCount: [6, 9],
      distractors: ['☁️', '🌙', '✈️', '🪐', '🛸', '☄️'],
      distractorCount: 14,
      moving: true,
      question: ['🚀 は いくつ？', '💫 は いくつ？'],
    },
  ],
};
